# Generated by Django 5.1.6 on 2025-03-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_password1_record_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='record',
            name='zip',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
