# Generated by Django 5.1.6 on 2025-03-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_record_zip_code_record_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
